### ISSUE TITLE
Use different event for stabilize

### ISSUE THREAD

**Issue by danymat** [luukvbaal/stabilize.nvim#1] opened 2021-10-19 04:55 UTC
Hello, and thank you for such great idea and plugin !
I feel like that the event used (CursorMoved) is too much work and could threaten the perceived velocity of the user:

https://github.com/luukvbaal/stabilize.nvim/blob/0b9d82a6aaf2ccb8e7c07f99ba463505de8033e8/lua/stabilize.lua#L88

Could you use a different event to achieve the same/closest result ?

**Comment by luukvbaal** [comment] 2021-10-19 10:04
I tried messing around with this but I'm not sure anything less frequent than `CursorMoved` is enough to properly keep track of the cursor position.

I tried using `WinLeave` but this resulted in unexpected behavior, probably due to the `vim.schedule` calls.

Even using `CursorHold` can lead to the cursor position not being saved properly if you open a window shortly after moving the cursor.

Anyways all that's being done is saving the cursor position, I doubt any slowdown can be perceived. 

May look into it again later.

**Comment by luukvbaal** [comment] 2021-11-12 13:33
Closing this as I don't think there is any room for improvement here with the currently available `autocmd`s.

Updating the cursor position on `WinLeave` works for closing a window but the windows are resized before `WinLeave` fires when opening a new window so the topline is already updated at that point.

**Closed as completed by luukvbaal** 2021-11-12 13:33 UTC
