### ISSUE TITLE
Does not work with Goyo

### ISSUE THREAD

**Issue by j-hui** [luukvbaal/stabilize.nvim#7] opened 2021-11-11 23:16 UTC
I sometimes use [Goyo](https://github.com/junegunn/goyo.vim) for editing.

When I try to open a `:Goyo` buffer, I get the following error:

```
Error executing vim.schedule lua callback: .../.vimplugins/plugged/stabilize.nvim/lua/stabilize.lua:55: Invalid window id: 1001
```

and no new window is created.

Goyo does not define a different filetype for the Goyo buffer, and I'm not really sure what `buftype` is checking, so I'm not sure how to disable stabilize.nvim for Goyo buffers (or if that'll even work). Goyo does provide user events `GoyoEnter` and `GoyoLeave` upon entering and leaving the buffer, but I'm not quite sure what to do with that.

**Comment by luukvbaal** [comment] 2021-11-11 23:19
I'll check if I can reproduce. I use a similar plugin [TrueZen.nvim](https://github.com/Pocco81/TrueZen.nvim) which works fine btw.

**Comment by j-hui** [comment] 2021-11-11 23:21
ooh @luukvbaal thanks for the tip! I'll check that out.

**Comment by j-hui** [comment] 2021-11-11 23:22
(though it would still be get to the bottom of why this doesn't work with Goyo---I'm trying to maintain compatability with vim and nvim < 0.5.0 to the extent possible)

**Comment by luukvbaal** [comment] 2021-11-11 23:32
I'm not entirely sure what Goyo does with it's windows and why it produces errors but since they have no content they don't need to be tracked by stabilize.nvim.

I would suggest changing your Goyo mapping to `noautocmd Goyo`, that should work.

**Comment by luukvbaal** [comment] 2021-11-11 23:35
https://github.com/luukvbaal/stabilize.nvim/commit/10bb37c82e94122be082651ee6ee58b5b2e51cb5 avoids the error but without `noautocmd` I have to run `Goyo` twice to make it work.

Hope changing your mapping to `noautocmd Goyo` works for you.

**Comment by j-hui** [comment] 2021-11-11 23:52
Ah thanks for the really fast fix!

Weird that without `noautocmd`, I need to run it twice.

When I run with `noautocmd Goyo`, my buftabline no longer shows up while in Goyo mode (though maybe this is a good thing, since the whole point is to remove visual noise).

**Comment by luukvbaal** [comment] 2021-11-12 13:34
Closing this because I think we've done all we can here. Any further issues should be fixed in user config.

**Closed as completed by luukvbaal** 2021-11-12 13:34 UTC

**Comment by j-hui** [comment] 2021-11-22 21:47
So I decided to look into what was up with this again. I'm not sure if there is a fix, but I figured I'd leave some notes in case @luukvbaal any of this seems easily fixable to you.

To construct the focused view of a buffer, Goyo works by [creating a new tab](https://github.com/junegunn/goyo.vim/blob/master/autoload/goyo.vim#L187) with a window for that buffer, and surrounding it with blank, unmodifiable ["pad"](https://github.com/junegunn/goyo.vim/blob/master/autoload/goyo.vim#L85) windows that place the buffer window in the center. To make sure the user can exit from this view cleanly, Goyo registers an [autocmd for the `TabLeave` event](https://github.com/junegunn/goyo.vim/blob/master/autoload/goyo.vim#L263) that removes this padding and the containing tab.

Stabilize conflicts with Goyo when Goyo constructs the new tab and pad windows, it triggers the [`WinNew` event](https://github.com/luukvbaal/stabilize.nvim/blob/master/lua/stabilize.lua#L91) that Stabilize is listening for, which eventually calls [`restore_windows()`](https://github.com/luukvbaal/stabilize.nvim/blob/master/lua/stabilize.lua#L24). This schedules a callback which eventually [switches windows](https://github.com/luukvbaal/stabilize.nvim/blob/master/lua/stabilize.lua#L37)---leaving the tab---to fix some cursor positions. In doing so, Stabilize triggers `TabLeave`, causing Goyo to turn itself off.

For some reason, when Goyo turns itself off, it doesn't manage to update Stabilize's `numwins` variable, which it [uses](https://github.com/luukvbaal/stabilize.nvim/blob/master/lua/stabilize.lua#L27) to figure out whether the window state changed, i.e., when it needs to go and fix the position of each window. This is why invoking `:Goyo` for the second time works.

I've tried a couple of fixes/workarounds:

- As @luukvbaal suggested, triggering `:Goyo` with `noautocmd` works, because doing so will not set off Stabilize's event handlers. However, this also means `:Goyo` will not trigger its own `GoyoEnter` and `GoyoLeave` user events, which are designed for the user to do things like apply custom modifications to the Goyo buffer.
- I tried asking Stabilize to additionally [ignore](https://github.com/luukvbaal/stabilize.nvim/blob/master/lua/stabilize.lua#L25) `TabLeave` between scheduling the callback and invoking it. While this solves the problem of needing to run `:Goyo` twice, it also prevents Goyo from automatically tearing down the padding windows when the main Goyo window is closed.

@luukvbaal , does anything here seem like it can be easily fixed, either with Stabilize.nvim or on Goyo's side? I'm just curious to know if there's a fix that will allow both plugins to work out of the box without any workarounds, and am happy to experiment more/make PRs.

**Comment by luukvbaal** [comment] 2021-12-20 17:07
@j-hui sorry for never getting back to you on this, I totally missed your detailed report.

Please check if https://github.com/luukvbaal/stabilize.nvim/commit/e97de689cbebb5a58603905db7f09107d86a147b has fixed the issue, I think it will have.

**Comment by j-hui** [comment] 2021-12-22 00:22
No problem @luukvbaal!

That seems to have worked. Thanks for fixing it!
